version: "3.8"

services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack
    network_mode: bridge
    ports:
      - "0.0.0.0:4510-4559:4510-4559"  # external service port range
      - "0.0.0.0:4566:4566"            # LocalStack Edge Proxy
    environment:
      SERVICES: secretsmanager,systemsmanager,dynamodb,s3
      DYNAMODB_IN_MEMORY: 1
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./.docker}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
    healthcheck:
      test: ["CMD", "curl", "http://localhost:4566/_localstack/health"]
      interval: "1s"
      timeout: "5s"
      retries: 5
      start_period: "1s"
