name: release
on:
  push:
    branches:
      - main
    paths:
      - version

permissions:
  id-token: write
  contents: read

defaults:
  run:
    shell: bash -ieo pipefail {0}

jobs:
  release:
    name: release ${{ matrix.packages.package }} ${{ matrix.packages.os }}
    runs-on: ${{ matrix.packages.os }}

    strategy:
      fail-fast: false

      matrix:
        packages:
          - {os: "ubuntu-22.04", package: "sdist"}
          - {os: "ubuntu-22.04", package: "wheel"}

    steps:
      - name: checkout repo
        uses: actions/checkout@v3

      - name: setup
        run: scripts/setup

      - name: package-${{ matrix.packages.package }}
        run: scripts/package-${{ matrix.packages.package }}

      - name: publish-${{ matrix.packages.package }}
        run: scripts/publish-${{ matrix.packages.package }}
