name: test
on:
  pull_request:
  push:
    branches:
      - master


# TODO(lijok): cache dependencies
# TODO(lijok): can we overwrite job names?
jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: true

      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        python-version:
          - "3.8"
          - "3.9"
          - "3.10"

    steps:
      - name: checkout repo
        uses: actions/checkout@v3

      - name: install python${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: run tests
        run: make all-test PYTHON_VERSION=${{ matrix.python-version }}
