name: test
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    name: ${{ matrix.test-type }} ${{ matrix.os }} python${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: true

      matrix:
        os:
          - "ubuntu-22.04"
#          - "macos-12"
#          - "windows-2022"
        python-version:
          - "3.8"
          - "3.9"
          - "3.10"
        test-type:
          - "unit-test"
          - "integration-test"
          - "property-test"
          - "functional-test"
          - "security-test"
          - "smoke-test"
          - "acceptance-test"
          - "performance-test"

    steps:
      - name: checkout repo
        uses: actions/checkout@v3

      - name: install python${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: cache python dependencies
        uses: actions/cache@v3
        with:
          path: .venv
          key: python-${{ matrix.python-version }}-${{ matrix.os }}-${{ hashFiles('pyproject.toml') }}

      - name: setup
        run: make setup
        env:
          PYTHON_VERSION: ${{ matrix.python-version }}

      - name: run tests
        run: make ${{ matrix.test-type }}
        env:
          PYTHON_VERSION: ${{ matrix.python-version }}
